version: '3.8'

services:
  telegram-bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: subtitle-bot
    environment:
      - PYTHONUNBUFFERED=1
      - FFMPEG_THREADS=4
    volumes:
      - ./temp:/app/temp
      - ./sessions:/app/sessions
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 6G
        reservations:
          cpus: '2'
          memory: 2G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
